### ISSUE TITLE
rename pnlViews

### ISSUE THREAD

**Issue by codog180** [Novik/ruTorrent#2615] opened 2023-12-11 18:29 UTC
### Is your feature request related to a problem?

Yes, unable to rename a newly created pnlView

### Describe the solution you'd like

Ability to rename a newly created pnlView instead of the the default "New View"

### Additional context

There does not seem to be any way to rename a view. Right clicking also causes JS errors which have been reported.

**Comment by stickz** [comment] 2023-12-19 11:36
Closing as duplicate of #2614. If you have any information to add, please do it there.

**Closed by stickz** 2023-12-19 11:36 UTC
Labels: duplicate
