### ISSUE TITLE
Keep ratio and uploaded value after using the command "Save to"

### ISSUE THREAD

**Issue by metafrastis** [Novik/ruTorrent#1277] opened 2016-06-04 13:27 UTC
When you use the command "Save to" in a torrent already completed for the purpose of move to another folder, the torrent got your values "uploaded" and "ratio" set to zero, the correct operation is to maintain the same original values, modifying only the destination folder.

**Comment by Novik** [comment] 2016-06-04 18:18
This behavior can't be corrected on the WebUI level. Try to write request to the author of rtorrent.

**Comment by ChemicalRascal** [comment] 2016-07-22 15:17
@Novik, I did some digging and it looks like it might be something that can be corrected at the WebUI level.

Inspection of [the relevant code](https://github.com/Novik/ruTorrent/blob/254551cc08311cebebfa0e1843168f5b1163628c/plugins/datadir/util_setdir.php#L211) shows that moving with fast resume _toggled on_ recreates the torrent file entirely, while having it toggled off does not, instead just performing `d.set_directory` and `d.set_directory_base` as appropriate.

Indeed, testing moving torrents around with fast resume toggled off found that the torrent uploaded/downloaded data and such was *not* reset, which I think isolates this bug quite handily.

I'm not well-versed enough in rTorrent and ruTorrent to know if fast resuming actually requires that the torrent be `d.erase`-d and recreated, but I'm going to assume that it probably... doesn't? It seems pretty weird if it does indeed require that happen.

**Comment by Novik** [comment] 2016-07-26 10:09
> I did some digging and it looks like it might be something that can be corrected at the WebUI level.

Sorry, but I can't see - what should be corrected.
'Fast resume' - is an user controlled option. It is intended for cases, when we have a very big torrent's data, and user can't wait for rehash after its moving (for example, I use this option for "Save as" function on rtorrent on the my ASUS router - a very slow configuration). And yes, if user will set this option - then some statistic data for torrent will be cleared. 
What is wrong?

**Comment by ChemicalRascal** [comment] 2016-07-26 11:28
Well, consider lines [234 to 244.](https://github.com/Novik/ruTorrent/blob/254551cc08311cebebfa0e1843168f5b1163628c/plugins/datadir/util_setdir.php#L234)

The key thing here is that ruTorrent forces the torrent to be entirely remade. This is, surely, overkill? From my usage, I _haven't_ seen rtorrent rehash data after a `Save To...` when fast resume _isn't_ selected, and given the data being used for testing was about a hundred and eighty gigabytes, I don't think the machine in question just did it quickly.

Again, that's with fast resume off, no hashing seems to happen.

**Comment by hlcb91** [comment] 2016-07-30 14:18
Situation:

01 - I do download a torrent of 2GB and it is successfully completed (my ratio at that moment is zero, of course)

02 - I leave sharing the torrent and it sends 6GB (my ratio at that moment is 3.0, ok)

03 - This torrent is located in "/home/rtorrent/download" and want to move it to the folder "/home/rtorrent/download/completed", so for that I use the command "Save to" and leave marked the options "Move files date" and "Fast resume" (they come already marked, by the way)

04 - I click OK and wait a few seconds for the refresh, the torrent in the list is updated, it is already in a new folder, check via FTP if really it was moved and confirm again, in fact the file has been successfully moved, BUT (problem is here) my ratio should be 3, becomes a value of zero, "uploaded" and "ratio" set to zero.

**Comment by yuvalbar84** [comment] 2017-03-17 10:08
Is there any updates regarding this situation? it is very annoying. I have to check my real ratio at the tracker's site after each moved download

**Comment by pbrink231** [comment] 2017-04-12 13:46
This is really annoying because i found the delete with data option fails sometimes.  I use save to to easily figure out what didnt get deleted because it is all that is left in the folder

I want to add that the any torrent that has not finished will not lose any information.

WORK AROUND
The work around is really easy but still should not be needed.  After clicking "Save to..." make sure to uncheck "fast resume".  I dont know what this does but it is unneeded and the source of the problem.  After clicking ok all torrents continued seeding/downloaded like normal with this unchecked.  All stats stayed the same with no reset.  It is checked by default so you need to make sure you uncheck it every time.

**Comment by bolhaskutya** [comment] 2019-03-15 22:25
I can confirm the issue is still unresolved.

**Comment by stephenjmcmahon** [comment] 2019-04-17 00:19
Hi, found this thread by Googling because I have been running into the same issue....will not use fast resume as pointed out above but would be nice if this acted differently...or maybe there's a really good explanation for this

**Comment by koblack** [comment] 2019-05-20 08:27
761fb7eaff4b51b1f3080350687d7e8edc0890b6 datadir plugin: disable fast resume by default

**Closed** 2019-05-20 08:47 UTC
