### ISSUE TITLE
Automove stopped working after update to 4.2x

### ISSUE THREAD

**Issue by ADz-83** [Novik/ruTorrent#2547] opened 2023-08-09 18:08 UTC
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Copied everything if upgrading to v4.0 or master
- [X] Web browser, ruTorrent and PHP version provided

### Tell us about your environment

Firefox 115.0.2 (64-bit)
ruTorrent 4.2.1
PHP 8.1.10

### Give us detailed steps to reproduce the error

Use Automove with add torrent label

### Tell us the error message

I recently updated to 4.2.1 and now automov doesn't move after torrent is completed and no data in the "finished" column.  I checked execute log and found this....

```
 php /srv/rutorrent/plugins/autotools/check.php /home/XXXX/torrents/rtorrent/download/xxxxxxx
---
 PHP Fatal error:  Uncaught ArgumentCountError: rawurldecode() expects exactly 1 argument, 3 given in /srv/rutorrent/php/utility/utf.php:170
Stack trace:
#0 /srv/rutorrent/php/utility/utf.php(170): rawurldecode()
#1 /srv/rutorrent/plugins/autotools/check.php(15): UTF::raw_url_decode()
#2 {main}
  thrown in /srv/rutorrent/php/utility/utf.php on line 170
Captured output:
```

**Comment by stickz** [comment] 2023-08-10 08:14
Thank you, looks like a regression. I will fix it tomorrow and release a hot fix.

**Comment by ADz-83** [comment] 2023-08-10 17:04
> Thank you, looks like a regression. I will fix it tomorrow and release a hot fix.

Thanks. Much appreciated 👍

**Comment by stickz** [comment] 2023-08-11 13:57
> > Thank you, looks like a regression. I will fix it tomorrow and release a hot fix.
> 
> Thanks. Much appreciated 👍

I have pushed a fix to the `v4.2` branch. https://github.com/Novik/ruTorrent/commit/9cb0e7cb78465598c9f9809dc261983d95dfdac3 Could you confirm this resolves your problem? And the autotools plugin works are intended? I will release the hotfix afterwards.

**Comment by ADz-83** [comment] 2023-08-11 21:48
> > > Thank you, looks like a regression. I will fix it tomorrow and release a hot fix.
> > 
> > 
> > Thanks. Much appreciated 👍
> 
> I have pushed a fix to the `v4.2` branch. [9cb0e7c](https://github.com/Novik/ruTorrent/commit/9cb0e7cb78465598c9f9809dc261983d95dfdac3) Could you confirm this resolves your problem? And the autotools plugin works are intended? I will release the hotfix afterwards.

Confirmed working.   Thanks 👍

**Comment by stickz** [comment] 2023-08-11 23:43
ruTorrent `v4.2.2` released to resolve problem. https://github.com/Novik/ruTorrent/releases/tag/v4.2.2

**Closed by stickz** 2023-08-11 23:43 UTC
Labels: bug, Priority-High, v4.2

**Comment by phene** [comment] 2023-08-17 00:35
@stickz Unfortunately, I'm seeing this:

```
PHP Fatal error:  Uncaught Error: Call to undefined function mb_convert_encoding() in /var/www/rutorrent/php/utility/utf.php:170
Stack trace:
#0 /var/www/rutorrent/plugins/autotools/check.php(15): UTF::raw_url_decode()
#1 {main}
  thrown in /var/www/rutorrent/php/utility/utf.php on line 170
```

I noticed there are a number of checks throughout the codebase for `function_exists('mb_convert_encoding')`, but there isn't one in these utility/utf functions.

Further reading suggests I need another php dependency to make that function available, but perhaps we still want to make these functions safe if php-mbstring is not available.
