### ISSUE TITLE
double click in "Upload File" menu can go through to the UI item behind

### ISSUE THREAD

**Issue by w4hnsinn** [Novik/ruTorrent#1866] opened 2019-04-04 19:36 UTC
I've searched but have not seen this reported. Sorry if I missed an existing report.

Steps to reproduce:
1. click "+" (Add Torrent)
2. click "Browse..." -> a new window "File Upload" opens
3. move this window so that a .torrent file displayed in it is right "above" one of the column headers of rutorrent (e.g. "Name")
4. double click the .torrent file

-> the column header will also be affected - the sorting changes accordingly.

I've verified this behavior with my primary browser (latest version of Waterfox) as well as the latest version of Firefox.

**Comment by Micdu70** [comment] 2019-04-04 20:08
Don't have this issue with Chrome. If Firefox can't create proper "File Upload" window... it's lame...

**Comment by w4hnsinn** [comment] 2019-04-04 20:18
mmh, fired up a quick install of google chrome portable to check that (73.0.3683.86 (Official Build) (32-bit)):

same issue!

**Comment by Micdu70** [comment] 2019-04-04 21:02
Can't reproduce on my Chrome installation (73.0.3683.86 (Official Build) (64 bits)).
On Firefox (66.0.2 (64 bits)), I can reproduce this issue.
My main browser is Brave (Chrome based browser) and can't reproduce it.

**Comment by Novik** [comment] 2019-04-09 09:18
This is problem of firefox browser. It can't be fixed on the application level.

**Closed by Novik** 2019-04-09 09:18 UTC
