### ISSUE TITLE
first element being a zero length string (REDUX, again!)

### ISSUE THREAD

**Issue by AlbeSure** [Novik/ruTorrent#1066] opened 2015-05-06 22:11 UTC
Referencing #896, #983 and #1056 

**Novik**-

While I do certainly appreciate your taking the time to respond to my previous thread (in #1056)
>> where can I find that release

>Try to see to the front page of project.

>> and does it include the fix to the folder function, and does that fix fully resolve the null path component issue?

>Try to check.

...this was really NOT the clear or direct reply that I asked for and had hoped to receive.

As you suggested, I was (of course) able to locate the most recent stable release version of ruTorrent v3.7 (Released Apr 10, 2015) from the front ruTorrent project page, available from...
https://bintray.com/novik65/generic/ruTorrent/3.7/view

...BUT there are:
> No release notes available for this version yet.

Certain developers (namely µTorrent and briefly Transmission, as well), IMHO, were needlessly aggressive and haphazard in their response to ruTorrent's long-standing "NON-standards compliant" first element being a zero length string bug [documented HERE] (https://trac.transmissionbt.com/ticket/5517), and this has created *significant* problems across the greater torrent sharing community!

Of course, ruTorrent is NOT a standalone program that I could just easily enough download, launch and verify functionality.  While your response DOES suggest to me that this issue may, indeed, have been resolved with the recent release of ruTorrent v3.7...there's just NO WAY that I could go to my seedbox provider and ask them to implement a major upgrade (such as updating to ruTorrent v3.7) with NO GUARANTEE that doing so would resolve this now very significant issue.

I do REALLY appreciate your considerable effort in developing and supporting ruTorrent (it is my preferred seedbox interface).  I have personally gone to bat in support of ruTorrent on *several* private torrent servers that I am a member of (including one prominent server that I am a "junior moderator" for)...and also [HERE] (https://forum.transmissionbt.com/viewtopic.php?f=2&t=16626) in the Transmission forums.

While it will NOT solve the problem of how to best "clean-up" the existing "NON-standards compliant" .torrent files...your providing a simple, clear and direct response (both here and in your v3.7 release documentation) could be a really great starting point in speeding adoption of ruTorrent v3.7 and that would be a really great benefit to the torrent sharing community as a whole!

So, with all that having been said, I return back to my original question:

**Novik**, could you please clarify if the "first element being a zero length string" bug has been fully resolved in the release version of ruTorrent v3.7?
 
 
Again, thank you SO MUCH for your considerable efforts in creating, developing and supporting ruTorrent!

Sincerely,
 
 
-A.S.

**Comment by JohnFlowerful** [comment] 2015-05-06 22:20
He's asking you to test whether the current fix has worked or not. One can only assume that the fix has  worked since no one has reported back.

**Comment by AlbeSure** [comment] 2015-05-06 23:23
**JohnFlowerful** wrote:
>He's asking you to test whether the current fix has worked or not. One can only assume that the fix has worked since no one has reported back.

OK, if that's the case...then it was unclear to me (and, if so, my sincere apologies).  The way I read ** Novik**'s comments in #1056 it sounded like he was being deliberately vague in his reply (maybe for some misplaced dramatic effect?), but I would be happy to learn that I was mistaken about this.

Just to be clear, so...there is an included (but NOT fully tested) "fix" in the release version of ruTorrent v3.7 for the "first element being a zero length string" bug, correct?  Has there been an active effort to test this "fix" and where could I track progress (as the 3 above referenced threads are the ONLY issues that I found in my searching, and they have all been closed)?

In my own testing (at least), this ruTorrent bug has been 100% reproducible (in earlier versions of ruTorrent) only when creating a NEW .torrent file that specifically includes a folder or directory (but is NOT present when a .torrent is created for an individual file).

If it might help, here is a link to some sample .torrent files that I created under ruTorrent v3.6 with and without an enclosing folder:
http://ge.tt/6jDSjH72/v/0


All the best!


-A.S.

**Comment by JohnFlowerful** [comment] 2015-05-06 23:51
I created a torrent with git HEAD
![http://puu.sh/hE72G/6c8c624f13.png](http://puu.sh/hE72G/6c8c624f13.png)
Is this what you wanted?

**Comment by AlbeSure** [comment] 2015-05-07 00:13
**JohnFlowerful**-

To be honest, I am not entirely 100% sure...

My interest here is simply in ruTorrent (most preferably a "stock", "release version") being able to produce fully "standards compliant" .torrent files that will be usable under all versions of  µTorrent and Transmission.

(...I, of course, get that the above image is showing the internal structure of a .torrent file, but I couldn't begin to tell if what it is displaying is fully "standards compliant", or not.)

**Comment by JohnFlowerful** [comment] 2015-05-07 00:26
Can you point me to a version of Transmission or uTorrent that is known to not work with ruTorrent's torrents?

**Comment by AlbeSure** [comment] 2015-05-07 03:07
**JohnFlowerful**-

The issue is fixed in the current stable build of Transmission, however, "first element being a zero length string" affected .torrent files are still broken in the current release version (Transmission 2.84), available (for MacOS) here:
http://download.transmissionbt.com/files/Transmission-2.84.dmg

To the best of my knowledge, the same "non-compliant" ruTorrent built .torrents are intentionally flagged and rendered NON-functional with ANY version of µTorrent NEWER than v2.2.1 (for PC) OR v1.8.4 (for Mac), including the current:
http://www.utorrent.com/downloads/complete/os/osx/track/stable

OR...
http://www.utorrent.com/downloads/complete/os/win/track/stable

**PLEASE NOTE:**  Caution should be exercised with installing µTorrent 3.4.2+ (for PC), or later, as I do NOT know if the silent installation of miner files has been resolved…
http://forum.utorrent.com/topic/95041-warning-epicscale-riskware-silently-installed-with-latest-utorrent/

More general information and discussion about the ruTorrent bug may also be found in my posts to the Transmission forum here:
https://forum.transmissionbt.com/viewtopic.php?f=2&t=16626

Hope that helps...and THANK YOU SO MUCH for looking further into this!

Kind reagards,


-A.S.

**Comment by JohnFlowerful** [comment] 2015-05-07 04:06
I tested [Transmission Qt 2.84.3](http://sourceforge.net/projects/trqtw/files/Transmission-Qt/2.8x/) and the latest version of uTorrent linked above. Transmission works, uTorrent doesn't.

Anyway, it's up to the Transmission and uTorrent devs to support the broken torrents now. There isn't really any other solution since modifying file order will change the torrent's hash... The cause of the problem has been fixed (~9 months ago), so that's a thing at least!

**Comment by Novik** [comment] 2015-05-07 05:18
> this ruTorrent bug has been 100% reproducible (in earlier versions of ruTorrent)

Earlier versions of ruTorrent is not interesting for me. Troubles in Transmission and uTorrnet too. 
You can reproduce error of torrent creation on the *current* version of ruTorrent?

**Comment by AlbeSure** [comment] 2015-05-07 09:31
@**JohnFlowerful**:  I actually wasn't entirely aware of a Transmission for PC client (Transmission, I believe, started out exclusive to the MacOS X platform, and they have of course has also branched into seedbox software), so I have no idea if the PC side ever removed support for .torrent files affected by the ruTorrent "first element being a zero length string" bug, BUT that the current µTorrent client won't open the file does make a strong case that this issue remains unresolved.

While Transmission developers DID briefly (for two release versions, v2.83 and the current v2.84, under the on the MacOS X platform) break support of the affected "NON-standards compliant" .torrent files, but thankfully they had a change of heart and the offending .torrent files are again usable in [the latest stable build (for MacOS X)] (https://build.transmissionbt.com/job/trunk-mac/lastStableBuild/).

So far as I know, µTorrent developers kicked this whole 'we are the damn standards compliancy police' idea off in the first place.  From reading the comments by their developers and seeing the unconscionable SHIT that they currently produce, I have very little hope for that they will ever again support these otherwise fully functional "NON-standards compliant" .torrent files.  The ONLY reason that support for this software matters to me at all is their VERY LARGE installed userbase.

I do take it that the .torrent files that you tested were originally created under the current release version of ruTorrent v3.7, correct?  IF this is the case, then it is quite possible that the "first element being a zero length string" bug has NOT been fully resolved.  One very compelling server-side solution that I have come across is in active use on PTP, I know NOTHING about the underlying technology, but here is a screenshot...
http://i.imgur.com/fLLgU55.png


@**Novik**:  I mentioned my findings with ruTorrent v3.6 simply because that is what I have access to currently (and in the hope that by doing so I might help facilitate further testing and isolation of this bug in the most recent release version v3.7, IF this bug is indeed still present).  Short of my being able to go to my seedbox provider, point them to this thread and STRONGLY suggest that they upgrade to v3.7 BECAUSE this significant issue has been resolved, I have NO ACCESS to the *current* release version of ruTorrent (nor do I see any compelling reason for my seedbox provider to "upgrade" v3.7 if this bug remains).

I agree 110% that it was a completely SHORT-SIGHTED and BULLSHIT move by µTorrent developers to drop support for the "NON-standards compliant" (but otherwise FULLY functional) .torrent files created under ruTorrent v3.6 and earlier (and, from the sound of it, this bug may well still be present in ruTorrent v3.7).

The bottom-line is that µTorrent developer's choice to drop support for these "NON-standards compliant" .torrents creates significant issues for the greater torrent sharing community AND (especially IF this continues to be left unresolved) and this no doubt lead to reduced marketshare/support for ruTorrent.  This problem begins to improve significantly when it can be clearly determined that this .torrent creation bug is NO LONGER present in ruTorrent v3.7 (or later if it is not yet resolved).

I would be more than happy to test any .torrent files created in ruTorrent v3.7 for usability, myself.  IF the bug remains unchanged, then simply creating a .torrent of a folder or directory (with, perhaps, a single text file inside) should be fully adequate for testing purposes!

Thank you BOTH so much! ;)


-A.S.

**Comment by JohnFlowerful** [comment] 2015-05-07 10:08
The torrents I tested were the ones you uploaded. The ones marked as invalid were indeed invalid. The [torrent I created](http://puu.sh/hEyzo/e3a4cc82ae.torrent) (the one in the screenshot) worked in all clients I tested.

You should really test this for yourself. It could be a works4me situation on my end, but I'm 99.5% sure that this issue has been resolved.

**Comment by AlbeSure** [comment] 2015-05-07 12:06
**JohnFlowerful** wrote:
> The torrents I tested were the ones you uploaded. The ones marked as invalid were indeed invalid. The [torrent I created] (http://puu.sh/hEyzo/e3a4cc82ae.torrent) (the one in the screenshot) worked in all clients I tested.

Good to know!  I feel like I was working under the presumption that the test .torrents that you reported about in your previous post were ones that you, yourself, had originally under ruTorrent v3.7...so, I do appreciate the clarification!  (Of course, as I had earlier stated, I created those sample files under ruTorrent v3.6.)

> You should really test this for yourself. It could be a works4me situation on my end, but I'm 99.5% sure that this issue has been resolved.

Viola!  I will say that all offending versions of µTorrent have been stricken and BANNED from my computer, however, in testing YOUR sample using Transmission v2.84 (for MacOS X), the .torrent file loads WITHOUT issue!  Granted, this a very narrow sample set...but as my results under ruTorrent v3.6 (as earlier stated) were 100% reproducible, this is compelling enough evidence for me to move forward now believing that the "first element being a zero length string" bug has, indeed, been resolved in ruTorrent v3.7.

THANK YOU (again) **Novik** for your hard work and dedication in creating, supporting and further developing this fine product...and to **JohnFlowerful** for *very* kindly going to the effort of helping to establish that **ruTorrent v3.7 does appear to now produce 100% "standard-compliant" .torrent files that load and are FULLY functional under current release versions of µTorrent and Transmission (among other popular torrent clients).**

Kind regards,

-A.S.

**Closed** 2015-05-12 10:44 UTC
