### ISSUE TITLE
Unable to sort columns when clicking once

### ISSUE THREAD

**Issue by delize** [Novik/ruTorrent#1195] opened 2016-02-11 05:08 UTC
Hello,

Based off of build/development release: 750a93e

I am unable to click to sort a column in chrome. Instead, currently it thinks I want to move the column to the left and the right, and doesn't actually resort to sorting. Instead it thinks that the mouse button has been held down and moved.

**Comment by KyleSanderson** [comment] 2016-02-11 06:14
I started seeing this in Chrome a couple releases ago, before that it worked for years (I'm running 3.4? haha). Whenever I have to sort the columns I use Firefox.

**Comment by Novik** [comment] 2016-02-26 08:56
What about Chrome version, client-side OS?
Can't reproduce this for Win10, Chrome 48.0.2564.116 m

**Comment by delize** [comment] 2016-02-28 06:14
Not sure what resolved this, but it occurred at the time of writing, now it seems to work.
Currently on Win 10,  48.0.2564.116 m as well. 

Considering this was 17 days ago, I am going to narrow it down to Win10 Chrome 48.0.2564.109 version, as that was the latest stable release for Chrome 17 days ago. Anything older then that, might apply to this ticket.

**Comment by KyleSanderson** [comment] 2016-02-28 06:44
I am still unable to sort by Finished or Added.

**Comment by shad00m** [comment] 2016-03-11 21:40
I had this on Windows 8.1 as well, now I'm on Windows 10.
I've had this for Years/Month with chrome but it only stops randomly working and then magically works again. It seems completely random.

**Comment by Nyago123** [comment] 2016-03-18 20:16
This is definitely still present, and I know I've seen it off and on as long as I've been using ruTorrent with Chrome myself, which is well over 3 years - so it's not just recent Chrome versions.  It does seem random and it's not super frequent but once it starts it's hard to get rid of. Usually a total client side system reboot will fix it for me.  Starting/stopping the WebUI does not.

But it's more of an annoyance than anything.  

The only thing I'd add is that even if this is likely a Chrome bug, it'd be nice to have an alternate ruTorrent hotkey, right-click menu (e.g. change the menu that comes up when clicking on the column header from only a column selection list to a nested menu with Sort>{ascending,descending} and Select Column>{column list}), a sort plug-in with dropdown menu, or some other way to sort on a column.

**Comment by thadius856** [comment] 2016-03-20 14:38
Same. 0.9.6/0.13.6 with Chrome 49.0.2623.87 m on Win 10. Was previously happening on Win 7 and 8.1 versions of Chrome as well. This has been happening for me for at least a year on a mix of the last 2-3 versions. Completely intermittent. Works just fine in Firefox 100% of the time.

When it happens, Chrome doesn't let me click to sort, but rather seems to assume I'm trying to reorder the columns and automatically goes to the four-way-move-arrows cursor and light the whole column header grey w/ blue outline.

**Comment by eriksperling** [comment] 2016-04-11 13:44
Same. The mouseup handler which does the self.Sort() call is not called in response to left button up. It *is* called in response to right button up.

Additionally: If I use a debugger, break the script anywhere, click left button on a column header, resume the script with F8, and then release left button, the handler is called and sorting works. So, some mousedown handler (skipped due to the debugger break and consequently lost mousedown event) seems to be preventing the mouseup handler from being called.

**Comment by Ineluctable** [comment] 2016-05-05 20:32
@Novik - I have the same issue as these guys, and it's a bit of a pain. It requires me to open up Firefox just to change my column sort. I'd love it if you can find a fix!

**Comment by alfton** [comment] 2016-05-19 07:55
same issue here, using linux mint 17.3 with lastest chromium installed

**Comment by thadius856** [comment] 2016-05-20 18:47
I wonder if it would be possible to write a simple plugin to send a mouseup
even as a stop-gap. I may look into this over the weekend.

**Comment by Harry3343** [comment] 2016-05-25 07:25
I've been having the same issue, stops working at random times - Windows 7, Chrome 50.0.2661.102 m. A workaround that I've been using is to hold the left mouse button (doesn't have to be on the column) and click the column with the middle mouse button (or vice versa). It's not perfect but I hope that helps.

**Comment by alfton** [comment] 2016-05-25 19:31
Ty Harry3343 for that tips..:P that did work for me

**Comment by djn123** [comment] 2016-06-25 08:55
Click and hold above the tab then move mouse over tab and release works for me.

**Comment by techjp** [comment] 2016-07-19 10:20
I also discovered that using both the left and middle buttons (or mouse wheel) together works. I just press them both at the same time, and it works every time. Was very frustrating until I figured that out!

**Comment by Novik** [comment] 2016-07-26 09:47
Sorry, but I can't to reproduce this issue. Very strange...

**Comment by Fugor** [comment] 2016-08-15 00:54
> Click and hold above the tab then move mouse over tab and release works for me.

> I also discovered that using both the left and middle buttons (or mouse wheel) together works.

Both works for me. Thanks for the work around.

**Comment by benjamintillman** [comment] 2016-08-15 02:03
Ok, I've been getting this issue on random occasions too. Clicking and holding the left mouse button somewhere above the column header, then moving your cursor down so it's on top of the column, and finally releasing the mouse cursor, causes the column to sort as per normal. Once you've done this once, the whole issue is gone and you can just click columns to sort again like normal (at least until the bug re-surfaces again).

To re-arrange columns you normally click and hold the left mouse button down on the column of your choice, and start dragging to where you want the column. The dragging process, while the the left mouse button is down, triggers some JavaScript to manage re-arranging the columns.

So, at a guess, the bug is that the JavaScript that is responsible for managing re-arranging columns is being left in an active state at some point. The next time a user tries to sort by a column, the re-arrange column code just kicks straight back in. It's active when it shouldn't be.

Now, I haven't tried to debug the code so the above is a bit of a pseudo-explanation I guess, but to anyone who is familiar with the JavaScript I think that might help narrow down where the issue is (what isn't being reset, or something, at some point, causing the 'click and drag' code to run with the 'drag').

What causes the issue initially? I have no idea. I'll keep an eye out and repost if I notice something, but it might not be necessary to know if you can figure out a more robust way of guarding that re-arrange column code.

**Comment by CDeLeon94** [comment] 2016-08-19 03:35
@benjamintillman I tried to use on of the'mouse down away > mouse up over the column' methods, and this allowed me to sort the columns I wanted. However, this did not allow me to subsequently click other columns to sort them. It immediately returns to trying to move the column.  
  
For a bit more info on what might be causing it, another work around I used was to assign a key on my logitech keyboard to mouse1 (Left click). I could then press this keyboard button while mousing over a column and the column would sort appropriately.  **However, I tried to do this mapping again to verify, and it seems to no longer work**

**Comment by CDeLeon94** [comment] 2016-08-19 03:36
I'd like to also mention, just in case this is related:  
I occasionally cannot click on tabs within Chrome, I hover over a tab press the mouse button but the tab does not activate. However, If I right click somewhere on Chrome, the left clicking on tabs begins working again.

**Comment by ericvolp12** [comment] 2016-09-12 18:59
Also experiencing this issue in Chrome on Windows 10.

Just a little bump.

**Comment by liquidox** [comment] 2016-10-10 07:35
Hadn't had this problem until recently. Am also using Chrome on Windows 10, quite annoying!

ruTorrent also interferes with the cxMousegestures addon, also annoying.

**Comment by asavah** [comment] 2016-11-04 17:54
It's really weird:

Win10 x64 chrome (54.0.2840.87m)- can reproduce
Ubuntu 16.10 google-chrome-stable(54.0.2840.90-1) and  chromium-browser                        (53.0.2785.143-0ubuntu1.1307) - can not reproduce in both.

(Almost) no addons or extensions, ublock disabled for ruTorrent url.

Chrom{e,ium} bug?

**Comment by michaelrw10** [comment] 2016-12-07 04:59
same here. been happening for at least 4 years, on and off. its completely random when it happens, but like others have said, once it starts, it is difficult to get rid of.  eventually you forget about it and then randomly starts working again.. until 6 months later, the same thing happens all over again

**Comment by TwoPiArrrr** [comment] 2016-12-18 01:10
I have this problem too at the moment, no idea how to fix it. I did however accidentally find a work around.

If you click and hold on of the torrents or an empty space in the torrent list, then release the click over the column header you want to sort by, it will register as a single click and successfully sort your torrent list.

**Comment by willgrnr** [comment] 2017-01-18 01:57
All the above workarounds work, however I have found the easiest to be to "Ctrl + Click" on the tab. Voila!

**Comment by chrcoluk** [comment] 2017-05-24 23:15
also confirm the problem on chrome, and workaround using both mouse buttons works.

**Comment by baz357** [comment] 2017-08-29 13:54
"Click and hold above the tab then move mouse over tab and release works for me."

"Hold the left mouse button (doesn't have to be on the column) and click the column with the middle mouse button (or vice versa)."

Those workarounds work for me (thanks!), "Ctrl + Click" does not work. (Chrome)

Would be great if this could be fixed.

**Comment by fouquetp** [comment] 2017-09-24 07:08
We are the 24th of 2017 September's month and... with Chrome 61 I still got the same problem...
One topic on stack exchange discuss of this problem, not specific to rutorrent but to chrome "In Chrome moving the element while handling its mousedown event prevents the click event from firing" : 
[](https://stackoverflow.com/questions/29151120/in-chrome-moving-the-element-while-handling-its-mousedown-event-prevents-the-cli)

I now use a workaround: I have set in my mouse driver (steelseries but should work with other brands) one button to fire when the button is released, not pressed and... it works normaly :D 💃

**Comment by tmchow** [comment] 2017-11-02 05:37
This still repros for me in Nov **2017**.  The workaround that worked for me was this:

> Hold the left mouse button (doesn't have to be on the column) and click the column with the middle mouse button (or vice versa)

**Comment by FrancisChung** [comment] 2018-08-11 22:12
I'm seeing this issue on 4K screens + Chrome. I'm not seeing this issue on other screen + browser configurations.
@tmchow 's suggestion works on 4K Screens as a workaround.

**Comment by KyleSanderson** [comment] 2018-08-12 02:26
That's completely a red herring and absolute noise unfortunately. Resolution has no bearing on this bug. Firefox is still unfortunately a pile of shit but Chrome still reliably reproduces this. This is an absolute code issue and can be resolved; someone just has to debug it.

**Comment by AndrewSav** [comment] 2018-08-12 02:28
>Resolution has no bearing on this bug. 
How do you know?

**Comment by KyleSanderson** [comment] 2018-08-12 02:31
Knowledge? I've had a multitude of panels and it's a perpetual issue. With that being said I've had tons of scaling issues, it's the same decade old box but 9k torrents shouldn't differ from 40k or 150k.

**Comment by KyleSanderson** [comment] 2018-08-12 04:35
Not a problem @FrancisChung. I've heard Ronald Reagan's children also have this problem so let's bring them in as they could have comments in relation to this JavaScript column sorting issue.

**Comment by joydashy** [comment] 2018-08-12 06:03
Haven't had this issue for some time, possibly related to having switched to https://github.com/jfurrow/flood

**Comment by fryfrog** [comment] 2018-10-11 04:15
I've had this issue off and on for ages, glad I finally searched and found the simple work-a-rounds.

**Comment by w-biggs** [comment] 2018-11-19 01:29
Still occurs for me, but that middle-click trick helps. It's kinda goofy that this has been an issue for as long as it has, though.

**Comment by bland328** [comment] 2018-12-05 21:54
For the record, using Chrome under Windows 10 on a 1920x1080 screen, I usually have this problem, but not always.

Restarting Chrome _sometimes_ gets it working again (but, of course, that also involves reconnecting to ruTorrent, so that might also be what gets it working).

Switching to Firefox _always_ gets it working.

**Comment by Micdu70** [comment] 2018-12-05 22:20
This issue was fixed in git version, 11 months ago.

**Comment by w-biggs** [comment] 2018-12-05 22:36
In #1637? There hasn't been a release since June '17, though.

**Comment by Micdu70** [comment] 2018-12-05 22:45
Yep this one. New release date is unknown... Ask @Novik about that.

**Comment by mzaur** [comment] 2018-12-16 02:09
I just started experiencing this issue. Windows 10, latest Chrome 71.0.3578.98. The issue is not present on Edge.

**Comment by mzaur** [comment] 2019-04-15 02:32
@Novik can you please submit a new version since this is already fixed? It's still an issue

**Comment by koblack** [comment] 2020-02-21 18:58
Fix table sorting in chrome #1637

**Closed by koblack** 2020-02-21 18:58 UTC

**Comment by AndrewSav** [comment] 2020-05-04 01:15
@koblack which release is this in?

**Comment by Micdu70** [comment] 2020-05-04 05:23
@AndrewSav ruTorrent v3.9

**Comment by AndrewSav** [comment] 2020-05-04 06:39
>v3.9 Novik released this on Apr 9, 2019

How is it possible? This release was before this was fixed.

**Comment by pingmurder** [comment] 2026-02-19 13:06
It looks like the fix for this was left out of a refactor and it's back for the current version (5.2.10)
Affected browsers: Chrome, Chromium-based (Arc, Edge, Brave, etc.)
  Works in: Firefox

  Root cause: Chrome fires phantom mousemove events on every mousedown/mouseup (click) even when the mouse hasn't physically moved. These phantom events have movementX === 0 and movementY === 0.

  In js/stable.js, the DnD instance's onRun callback unconditionally sets isMoving = true on any mousemove. When onFinish fires on mouseup, it checks isMoving — if true, it calls colDragMoveEnd() (column reorder) instead of
  Sort(). So every click in Chrome triggers the drag path instead of the sort path.

  History: This was previously fixed in PR #1637 using an ignoreNextMove boolean flag, but that fix was lost when the codebase was refactored to use the DnD class.

  Fix: In js/stable.js, in the onRun callback of the DnD constructor (~line 164), add a guard to ignore zero-movement mousemove events before setting isMoving:

  onRun: (ev) => {
      if (this.isResizing) {
          this.colDragResize(ev);
      } else {
          // Ignore phantom mousemove events (Chrome fires mousemove on click
          // even when the mouse hasn't moved, which prevents sorting)
          if (ev.originalEvent.movementX === 0 && ev.originalEvent.movementY === 0) return;
          this.isMoving = true;
          this.isSorting = false;
          this.colDragMove(ev);
      }
  },

  Related issues: #1195, #1685, PR #1637
