### ISSUE TITLE
[Feature Req] Rename torrent

### ISSUE THREAD

**Issue by Moodkiller** [Novik/ruTorrent#1026] opened 2015-03-07 10:09 UTC
As is the same in uTorrent, the ability to rename the actually torrent would be beneficial for sorting and filing all the torrents one might have. Not to mention to fix the mess of people who don't know how to label torrents in the first place. 

I know this will probably fall back to the rtorrent side of things, but Im thinking if there is a way to link the .torrent loaded to a text file for example, which will have the prefered name (that you edited through ruTorrent) and have it apply this new name to the relative torrent?

Or perhaps a modification of this plugin (http://forums.rutorrent.org/index.php?topic=695.0) to rename the actually torrent file and not the files within a torrent?

**Comment by nVitius** [comment] 2016-04-05 01:55
I know this is an old request, but I think this would be really awesome to have.

**Comment by scottchiefbaker** [comment] 2017-03-19 00:58
I'm still looking for a way to do this. I would love this feature (or another plugin to do it).

**Comment by Fleshgrinder** [comment] 2020-03-17 16:35
#1985 might be a duplicate of this issue. In any event, maybe https://github.com/Fleshgrinder/rutorrent-rename is what you are searching for?

**Closed** 2020-10-29 13:23 UTC
Labels: wontfix
