### ISSUE TITLE
Caching issue with XMLRPC

### ISSUE THREAD

**Issue by SSoft7** [Novik/ruTorrent#1911] opened 2019-07-15 16:44 UTC
Hi,

I am using ruTorrent with rtorrent (connected using Unix socket).
Sometimes I get the following error when trying to open the 'Settings' menu ( even though Unix socket is working properly.)

> Bad response from server: (500 [error,getsettings]) Warning: XMLRPC call is failed.

This problem can be fixed by clearing the browser cache and reloading the rutorrent page. **But I need to find the exact file which is causing this issue.**

## Additional Info
Browser: Chrome Version 75.0.3770.100 (Official Build) (64-bit)
ruTorrent: v3.9 (release version)

1. Request
```
curl 'http://rtorrenthost.com/rutorrent/plugins/httprpc/action.php' \
-H 'Authorization: Basic Z2lnYXVzZXIxOjEyMzQ1Ng==' \
-H 'Origin: http://rtorrenthost.com' \
-H 'Accept-Encoding: gzip, deflate' \
-H 'Accept-Language: en-US,en;q=0.9' \
-H 'Content-Type: application/x-www-form-urlencoded' \
-H 'Accept: application/json, text/javascript, */*; q=0.01' \
-H 'Referer: http://rtorrenthost.com/rutorrent/' \
-H 'X-Requested-With: XMLHttpRequest' \
-H 'Cookie: SID=v60SlwbaFSrEL2vQRbaIqj8oMPiwXzJ2; PHPSESSID=1tkcl0psmc5ufffpjlb23rjd9h;' \
-H 'Connection: keep-alive' \
-H 'DNT: 1' \
--data 'mode=stg' \
--compressed --insecure
```

2. Response
`Warning: XMLRPC call is failed.`

3. Content of /tmp/errors.log (These are the exact errors right after the above request)
https://pastebin.com/raw/DqCb5JhV
So, If someone can point out which file is causing this, I can disable caching for that on the webserver.

**UPDATE:  TL;dr - I believe rTorrentSettings::get() is a little buggy, it does not check if cache file exists and tries to load it which is the cause of this issue. That's all.**

**Comment by Micdu70** [comment] 2019-07-15 17:06
You don't say which browser and version you use... It's an important info.

**Comment by SSoft7** [comment] 2019-07-15 17:19
I almost forgot that I have updated the original post.

Thanks.

**Comment by Micdu70** [comment] 2019-07-15 17:45
What about rtorrent/libtorrent version? And how/where do you installed them?

**Comment by SSoft7** [comment] 2019-07-15 18:02
Hello,

rTorrent version 0.9.6
libTorrent version 0.13.6

I have built them from source and source is downloaded from here https://rakshasa.github.io/rtorrent/.
I would like to **mention** again that, clearing the browser cache (one time) fixes the issue and happens again if I delete the user and create the user and reconfigure everything. 
Let me know if there is anything else I should mention :-)

**Comment by Micdu70** [comment] 2019-07-15 18:07
I think I found the issue but you will need to install ruTorrent via git. ;)

**Comment by SSoft7** [comment] 2019-07-15 18:14
Hi, 
httprpc plugin is already enabled. please check the screenshot
![image](https://user-images.githubusercontent.com/9930156/61238339-1142da80-a75a-11e9-809f-46bfaee00258.png)

btw, I am using Unix socket (just for info)
```
 $scgi_port = 0;
 $scgi_host = "unix:///var/run/.rtorrent.sock";
```

> I think I found the issue but you will need to install ruTorrent via git. ;)

It would be nice if you can mention which files are responsible for this.

**Comment by Micdu70** [comment] 2019-07-15 18:25
I don't think it's about a file, it's about outdated RPC commands (see in `/tpm/errors.log`):

> <member><name>faultCode</name>
> <value><i4>-506</i4></value></member>
> <member><name>faultString</name>
> <value><string>Method 'get_hash_interval' not defined</string></value></member>
> </struct></value>
> <value><struct>
> <member><name>faultCode</name>
> <value><i4>-506</i4></value></member>
> <member><name>faultString</name>
> <value><string>Method 'get_hash_max_tries' not defined</string></value></member>
> </struct></value>
> <value><struct>
> <member><name>faultCode</name>
> <value><i4>-506</i4></value></member>
> <member><name>faultString</name>
> <value><string>Method 'get_hash_read_ahead' not defined</string></value></member>

These 3 commands do not exist in rTorrent >= 0.9.0 and are replaced by "cat" if you use the httprpc plugin.

**Comment by Micdu70** [comment] 2019-07-15 18:49
Can you test this => In ruTorrent on Chrome, open "Inspector" ( CTRL + MAJ + i ) and go in "Console" then type below:
`theWebUI.systemInfo.rTorrent.iVersion>0x900`
What's the result?

**Comment by SSoft7** [comment] 2019-07-15 19:06
> theWebUI.systemInfo.rTorrent.iVersion>=0x900

![image](https://user-images.githubusercontent.com/9930156/61241687-a85f6080-a761-11e9-97a3-7e32432800c0.png)

**Comment by Micdu70** [comment] 2019-07-15 19:11
It's okay... so I don't know... can you share more `/tmp/errors` lines?

**Comment by SSoft7** [comment] 2019-07-15 19:19
Actually, I have pasted complete error log, (from loading rutorrent page to clicking settings icon).
Then every time I click settings, the same thing is repeated in the log file. so I have collected log for a single click.

**Comment by Micdu70** [comment] 2019-07-15 19:32
Did you restart your webserver and php-fpm services after ruTorrent 3.9 install? Do it anyway...
I can reproduce your issue if I change this line in "plugins/httprpc/action.php":
https://github.com/Novik/ruTorrent/blob/85d7a4f02ad1e89833285ec662a753f7f304e81e/plugins/httprpc/action.php#L167
Changes good ">=" to a wrong "<" comparaison.

Try to comment this line (add `//` at the start of the line) and save. Then try again. ^^

**Comment by SSoft7** [comment] 2019-07-15 19:41
> Did you restart your webserver and php-fpm services after ruTorrent 3.9 install? Do it anyway...
Yes, I am doing it often.

> Try to comment this line (add // at the start of the line) and save. Then try again. ^^
Great, surprisingly this works, I think this a probably a bug in ruTorrent?

**Comment by Micdu70** [comment] 2019-07-15 19:50
So it's a PHP issue => Can't properly read rTorrent version
To check that, you need to add this line, before the previously commented line:
`echo('rTorrent version: '.rTorrentSettings::get()->iVersion);`
Then refresh ruTorrent and click "Settings", you will see an error message containing rTorrent version.

**Comment by SSoft7** [comment] 2019-07-15 20:08
well, I have a completely unexpected output. looks like have of an array :-(

> rTorrent version: [1,"0","0.0.0.0","6881","\/home\/rtuser\/downloads\/rtorrent\/","0","","","","","","","0.0.0.0","1","0","137438953472","3435973836","128","32","100","-1","50","100","-1","1","1","1","0","1","51953-51973","262144","5120","0","0.0.0.0","0","0","0","0","\/home\/.sessions\/","1","1","-1",".part","900","600","

**Comment by Micdu70** [comment] 2019-07-15 20:15
Everything between [] is the results of all RPC commands but it's normal. ;)
So the variable `rTorrentSettings::get()->iVersion` is empty, rTorrent version isn't readable..
Why? I don't know... :(

**Comment by SSoft7** [comment] 2019-07-15 20:21
> Everything between "[ ]" is the result of all RPC commands but it's normal. ;)

The closing bracket `]` is not there if you notice carefully. (I have double checked this.)
You have said this line `echo('rTorrent version: '.rTorrentSettings::get()->iVersion);`
So,
`rTorrentSettings::get()->iVersion`
is equal to
`[1,"0","0.0.0.0","6881","/home/rtuser/downloads/rtorrent/","0","","","","","","","0.0.0.0","1","0","137438953472","3435973836","128","32","100","-1","50","100","-1","1","1","1","0","1","51953-51973","262144","5120","0","0.0.0.0","0","0","0","0","/home/.sessions/","1","1","-1",".part","900","600","`
This whole string, isnt it?

**Comment by SSoft7** [comment] 2019-07-15 20:40
Just for info, rtorrent version is visible when I clear browser cache and reload.

**Comment by Micdu70** [comment] 2019-07-15 21:02
Check PHP and webserver logs too. ;)

**Comment by SSoft7** [comment] 2019-07-15 21:30
Yep, I have checked them, i am getting 500 error from nginx still no such logs in server's error log /php-fpm log.
I have enabled php logs in php.ini, php-fpm logs are turned on too. still nothing.
Adding this to ruTorrent/plugins/httprpc/action.php does not help either. :-(
```
error_reporting(-1);
ini_set("display_errors","On");
```
I have tried curl command which returns also the same result as on the browser. Since curl have no cache it is contradicting with my earlier assumption.
Yet a clear cache and refresh is the fix. this is very weird issue.

**Comment by Micdu70** [comment] 2019-07-16 05:51
Hello again,
Is it possible to me to get 'root' SSH access and ruTorrent too? I would like to debug this strange thing.
Here is my email => Micdu70 |@| gmx |.| fr

**Comment by SSoft7** [comment] 2019-07-16 15:44
sent email.

> Hello again,
> Is it possible to me to get 'root' SSH access and ruTorrent too? I would like to debug this strange thing.
> Here is my email => Micdu70 |@| gmx |.| fr

**Comment by Micdu70** [comment] 2019-07-17 07:19
Can't reproduce this issue on git master version...
Using git master is recommended when possible.

**Comment by immobilia** [comment] 2020-04-18 22:07
After upgrading to Debian 10 and PHP 7.4, same initial problem :
> Bad response from server: (500 [error,getsettings]) Warning: XMLRPC call is failed.

ruTorrent upgrade method : v3.6 to v3.9 with "cp -r" (keeping old plugins not present in .tar.gz)

Fixed with fresh install via git clone.

**Closed** 2020-11-14 22:24 UTC
Labels: wontfix
