### ISSUE TITLE
Problem with Rutracker_check plugin (rutracker.org)

### ISSUE THREAD

**Issue by IvanShift** [Novik/ruTorrent#2056] opened 2020-05-22 11:02 UTC
Hello!
I am trying to use this plugin to autoupdate torrents from rutracker.org but it's not working( 
Every time I receive message: "Probably deleted", but it is updated, not deleted. 
This plugin works fine with other trackers except rutracker.org. 
What should I check to find solution of this problem?

**Comment by hapylestat** [comment] 2020-05-22 17:52
Check that you have access to **rutracker.org** and **api.rutracker.org** and the address is not blocked for you.  STE_DELETED status returned if http client failed to fetch the torrent file (i.e. got other code than HTTP 200, which is considered as success)

**Comment by IvanShift** [comment] 2020-05-22 17:58
Yes, I can access to rutracker, this is example of wget from container with ruTorrent:
![изображение](https://user-images.githubusercontent.com/64527940/82695872-a104bf80-9c6e-11ea-8ae4-22d49e8053dc.png)
But I have no idea how to login and download .tracker-file using wget. Or I shouldn't do it because wget can access to rutracker?
What else can I test?

**Comment by IvanShift** [comment] 2020-05-27 07:39
I also checked with the wrong username and password and get the same error. 
Why could this happen?

**Comment by sun1ight** [comment] 2020-11-10 12:48
Same error "Probably deleted", I can access to rutracker from host with installed rutorrent (api, etc). login/password correct. Other trackers work fine.
ruTorrent v3.10

**Comment by Novik** [comment] 2020-11-11 11:50
Check this functionality right now - for me all works correctly.

**Comment by sun1ight** [comment] 2020-11-11 11:57
On actual torrent status "No update required"
On updated torrent status "Probably deleted"
How can I debug what the problem is?

**Comment by Novik** [comment] 2020-11-11 12:14
First of all plugin trying to receive hash of torrent from forum, here -
https://github.com/Novik/ruTorrent/blob/master/plugins/rutracker_check/trackers/rutracker.php#L12
If this hash is equl to actual hash, then all OK (https://github.com/Novik/ruTorrent/blob/master/plugins/rutracker_check/trackers/rutracker.php#L15)
Otherwise plugin trying to download .torrent file - https://github.com/Novik/ruTorrent/blob/master/plugins/rutracker_check/trackers/rutracker.php#L18
And "Probably deleted" means - plugin can't do that.

**Comment by sun1ight** [comment] 2020-11-11 12:41
1) Tested on: romancin/rutorrent (current setup), linuxserver/rutorrent, custom setup with ruTorrent v3.10 from github
2) Access to api and https://rutracker.org, trackers, etc - not blocked (four times checked with wget from nas), login/password correct and no special characters (before there was same problem if the login was in Russian)

**Comment by IvanShift** [comment] 2020-11-11 12:44
My problem is still exist. None of updates are helped for me. I'm using docker container linuxserver/rutorrent. Is it possible to show some debug info?

**Comment by Novik** [comment] 2020-11-19 12:21
@sun1ight 
Sorry, but for fixing something I must see on this something. But I can't reproduce this error locally.
If you can give me SSH + ruTorrent credentials for account with this error, then mail me to the novik65@gmail.com.
(For SSH I need ability to make changes in the ruTorrent files).

**Comment by sun1ight** [comment] 2020-11-19 12:27
Okay, I'll make a dedicated test VM for you and give you access via email

**Comment by sun1ight** [comment] 2020-11-19 14:38
Sent you an email with all accesses to the test VM

**Comment by Novik** [comment] 2020-11-19 19:46
For account 'RUTracker' try to 
1) Turn on 'Enabled' checkbox
2) Fill your credentials.

![2020-11-19_22h41_43](https://user-images.githubusercontent.com/1230409/99716034-a7a6af00-2ab8-11eb-923b-eeacc61ab487.png)

**Comment by sun1ight** [comment] 2020-11-19 19:51
Аккаунт вписал, все равно не работает.
Logged into my account, it still doesn't work.

чт, 19 нояб. 2020 г. в 22:46, Novik <notifications@github.com>:

**Comment by sun1ight** [comment] 2020-11-19 19:52
Logged into my account, it still doesn't work.

**Comment by Novik** [comment] 2020-11-19 21:53
As result: you have too old version of User-Agent in the ruTorrent config.php.
Corresponding changes in the ruTorrent core was be applied 9 months ago:
https://github.com/Novik/ruTorrent/commit/0da161d21a1d2d850b079b52e70f0138bcac2cfe

I changed User-Agent to the modern version in your config.phph and now all works.

**Comment by sun1ight** [comment] 2020-11-19 22:36
Thanks, rutracker is working now, I checked it on the main server. I transferred the configs and did not notice that the user agent had changed there.

**Closed** 2021-06-18 01:52 UTC
Labels: wontfix
