### ISSUE TITLE
time finished gets not updated

### ISSUE THREAD

**Issue by FunThomas76** [Novik/ruTorrent#2599] opened 2023-11-17 06:59 UTC
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Firefox 119.0.1
ruTorrent: 4.2.8
OS: Windows 10 x64

### Tell us how you installed ruTorrent

fresh install from seedhost.eu

### Describe the bug

the time finished of the completed files will not refresh on the website 
so for a torrent the time shows 56m 11s and on the old 4.0.2 Version it got refreshed all 30 sec or so
but now on 4.2.8 it stays the same time until i make a manual reload of the webpage in Firefox

### Steps to reproduce

Download a torrent and watch the time finished

### Expected behavior

the time finished gets updated all 30 sec or with every refresh cycle

**Comment by stickz** [comment] 2023-11-17 07:36
This is not related to the ruTorrent version. It caused by rTorrent.

**Comment by stickz** [comment] 2023-11-18 16:16
Fixed in [v4.2.9](https://github.com/Novik/ruTorrent/releases/tag/v4.2.9).

**Closed by stickz** 2023-11-18 16:16 UTC
Labels: bug, v4.2, Confirmed
