### ISSUE TITLE
STOP and START - error "Bad response from server: (500 [error, list]) Link to XMLRPC failed. May be, rTorrent is down?"

### ISSUE THREAD

**Issue by free-storage** [Novik/ruTorrent#2230] opened 2021-12-14 15:43 UTC
Hello.

Most of the random torrents are paused and they do not start. If you press STOP and then press START, then the error "Bad response from server: (500 [error, list]) Link to XMLRPC failed. May be, rTorrent is down?" and the server crashes.

Everything worked well at first. After a while it broke.

I've tried deleting all torrent files and adding them over again. But the problem does not go away, somehow it breaks down again.

What to do?

**Comment by Pingblue** [comment] 2021-12-15 09:32
The error your describing is normally caused by lack of available space.

**Comment by free-storage** [comment] 2021-12-15 10:40
@Pingblue We have seedbox 12 TB of disk space. Currently 49% of disk space is used.

**Comment by Pingblue** [comment] 2021-12-15 10:55
If rtorrent is crashing there is normally an error displayed inside the rtorrent session.

**Comment by free-storage** [comment] 2021-12-15 11:08
@Pingblue 

When I try to start torrents:
[15.12.2021 18:04:56] WebUI started.
[15.12.2021 18:05:24] Bad response from server: (500 [error,list]) Link to XMLRPC failed. May be, rTorrent is down?

Next

When I reload the page:
[15.12.2021 18:06:10] WebUI started.
[15.12.2021 18:06:10] No connection with rTorrent. Check if it's running. Check that the $scgi_port and $scgi_host parameters in the config.php file match the value of the scgi_port variable in the rTorrent configuration file.

And only reboot helps to start the server.

**Comment by Pingblue** [comment] 2021-12-15 11:14
Yes thats rutorrent but what about rtorrent.

**Comment by free-storage** [comment] 2021-12-15 11:33
@Pingblue I have no access to them. I'll try to ask support. They answer for a very long time and cannot help. (((

**Comment by free-storage** [comment] 2021-12-15 12:24
@Pingblue If I remove all torrents and add some, then everything works fine. But if I add all the torrent ~ 2200 pieces, then until a certain moment it can work and then everything will break again.

But this is hardly a problem in quantity. Because when it was ~ 2000 everything worked fine too. And then it stopped working well.

**Comment by free-storage** [comment] 2021-12-15 15:29
@Pingblue The support said that they did not write logs and could not help. And what to do ...

**Comment by n1ce-0ne** [comment] 2021-12-16 00:10
@free-storage how old is the install & what versions, maybe a reinstall might help?

**Comment by free-storage** [comment] 2021-12-16 08:09
@n1ce-0ne rTorrent 0.9.6/0.13.6. I cannot reinstall because there is no access. Service support doesn't want to do anything.

**Comment by n1ce-0ne** [comment] 2021-12-16 08:38
@free-storage about all you can do then is try trim the total amount down to below 2000 to an amount where its stable again,
then work towards moving to another host like Micdu70 suggested,
sounds like a lousy host if you haven't even got an option to reinstall.

i use the same version & from my experience at around the 2000 mark things can become problematic,
now mines always between 600-1000 & runs much smoother.

**Comment by free-storage** [comment] 2021-12-16 09:17
@n1ce-0ne  Can you recommend a good seedbox? Long lasting.

**Comment by n1ce-0ne** [comment] 2021-12-16 23:57
@free-storage naa sorry but many exist, have a good look about it shouldn't take too long before you find one worth trying.

**Comment by stickz** [comment] 2021-12-26 02:43
@free-storage You can purchase a dedicated server. I have an rtinst script, where I've fixed all these problems with rTorrent and ruTorrent. I'm currently at 5154 torrents without any issues. Other than the hardware having trouble keeping up.

All you have to do is install Ubuntu 20.04 and create a new user with sudo access. This script should do the rest for you.
https://github.com/stickz/rtinst

**Closed** 2022-08-16 01:15 UTC
Labels: wontfix

**Comment by Merlincool** [comment] 2025-01-01 14:37
> @free-storage You can purchase a dedicated server. I have an rtinst script, where I've fixed all these problems with rTorrent and ruTorrent. I'm currently at 5154 torrents without any issues. Other than the hardware having trouble keeping up.
> 
> All you have to do is install Ubuntu 20.04 and create a new user with sudo access. This script should do the rest for you. https://github.com/stickz/rtinst

Yes but it crashes again when it's Over 7000 torrents in my case
