### ISSUE TITLE
Unpack does not work

### ISSUE THREAD

**Issue by blixten85** [Novik/ruTorrent#2421] opened 2022-12-22 16:59 UTC
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Linux raspberrypi 5.15.76-v7l+ #1597 SMP Fri Nov 4 12:14:58 GMT 2022 armv7l GNU/Linux
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

### Tell us how you installed ruTorrent

sudo rtsetup

### Describe the bug

unrar: invalid option -- 'a'
Try `unrar --help' or `unrar --usage' for more information.

### Steps to reproduce

right click file and choose unpack

**Comment by stickz** [comment] 2022-12-26 13:00
@blixten85 Please type `unrar --help` in terminal and provide us the output. It looks like the command syntax was changed.

**Comment by blixten85** [comment] 2022-12-26 13:52
> @blixten85 Please type `unrar --help` in terminal and provide us the output. It looks like the command syntax was changed. Also, ensure you're running ruTorrent v4.0-beta3 or master. We no longer support ruTorrent v3.10. https://github.com/Novik/ruTorrent/releases/tag/v4.0-beta3

unrar --help
Usage: unrar [OPTION...] ARCHIVE [FILE...] [DESTINATION]
Extract files from rar archives.

  -x, --extract              Extract files from archive (default)
  -t, --list                 List files in archive
  -f, --force                Overwrite files when extracting
      --extract-newer        Only extract newer files from the archive
      --extract-no-paths     Don't create directories while extracting
  -p, --password             Decrypt archive using a password
  -?, --help                 Give this help list
      --usage                Give a short usage message
  -V, --version              Print program version

Report bugs to <benasselstine@canada.com>.

**Comment by stickz** [comment] 2022-12-26 14:30
Thank you @blixten85. The problem is your `raspberrypi` is running a different version of `unrar`. I can resolve this problem and support your operating system, but I will require your help.  

I need you type `uname -p` in terminal. The purpose is to support arm in the bash script. I need to know the output.

**Comment by blixten85** [comment] 2022-12-26 14:33
uname -p
unknown

**Comment by stickz** [comment] 2022-12-26 14:34
Okay, try `uname -a`. I'm looking for some information I can use to detect your platform.

**Comment by blixten85** [comment] 2022-12-26 14:38
uname -a
Linux raspberrypi 5.15.76-v7l+ #1597 SMP Fri Nov 4 12:14:58 GMT 2022 armv7l GNU/Linux

**Comment by stickz** [comment] 2022-12-26 15:41
Thank you. I added support for raspberrypi unrar. Could you give it a try and see if works? https://github.com/Novik/ruTorrent/commit/c78a3c39ac085e6abb86ad4ab6001570a4f59552

Download the zip then extract the `plugins/unpack` folder.
https://github.com/Novik/ruTorrent/archive/c78a3c39ac085e6abb86ad4ab6001570a4f59552.zip

**Comment by blixten85** [comment] 2022-12-26 16:21
1453] Uncaught TypeError: Cannot read properties of undefined (reading '0')

**Comment by stickz** [comment] 2022-12-26 16:49
Clear your web browser cache and try again. It doesn't like that you just changed files. Are you running ruTorrent version 4?

**Comment by blixten85** [comment] 2022-12-26 16:53
Cleared, same error.

rtversion
rtorrent installed: 0.9.8
rtorrent available:

RuTorrent installed: 3.10
RuTorrent available: 4.0

rtinst
Current Release: rtinst v1.8.20
This is the latest release

**Comment by stickz** [comment] 2022-12-26 16:55
Hmm, you're not running version 4. Here's the commands to upgrade the version. It will install my latest changes.

Run the ruTorrent upgrade. Select the master branch, not a stable release. My latest commit will install automatically.
`sudo rutupgrade`

Afterwards, delete the autodl-irssi plugin. (backup it up first!!!) Then reinstall the version 4.
Do `sudo rm -r /var/www/rutorrent/plugins/autodl-irssi` first.
`git clone https://github.com/swizzin/autodl-rutorrent.git /var/www/rutorrent/plugins/autodl-irssi`

**Comment by blixten85** [comment] 2022-12-26 16:58
Ok, now i get 
403 Forbidden
nginx

**Comment by stickz** [comment] 2022-12-26 17:00
Run this command `sudo chmod -R 777 /var/www/rutorrent/plugins`. nginx will fix the permissions later.

**Comment by blixten85** [comment] 2022-12-26 17:01
Still the same

**Comment by stickz** [comment] 2022-12-26 17:02
Restart nginx.

**Comment by blixten85** [comment] 2022-12-26 17:05
i have

**Comment by stickz** [comment] 2022-12-26 18:15
Check nginx service status and logs. It will say what is happening.

**Comment by blixten85** [comment] 2022-12-26 18:18
it's up and running, nothing in the logs, it's the webpage that is no longer accessible.
Do i need to re-install rtorrent?

**Comment by stickz** [comment] 2022-12-26 18:21
This is a privileges issue. It should be working with chmod. 403 forbidden happens when you're not able to access the files on the web server. I know... run `rtpass` to reset your user profile on ruTorrent. perhaps that will help.

**Comment by blixten85** [comment] 2022-12-26 18:22
still the same

**Comment by stickz** [comment] 2022-12-26 18:39
Clear your web browser cache. It shouldn't be doing this, unless you're cached. There's no reason for this unexplained behaviour.

**Comment by blixten85** [comment] 2022-12-26 18:40
i'l just re-run the setup instead, the cache is cleared and i also force refresh with shift+F5

**Comment by blixten85** [comment] 2022-12-26 19:20
It still fails with unpack after re-install

**Comment by stickz** [comment] 2022-12-26 22:43
What is the error message? Does it produce any results? Are you using ruTorrent v4.0?

I don't have the same version of unrar as you. It's hard to test it. This version is specific to ARM.

**Comment by blixten85** [comment] 2022-12-27 04:42
I think it's something wrong with unrar tbh, i can't do it in the commandline either, no command works. 
This works perfectly tho. https://raspberrypi.stackexchange.com/questions/94284/installing-equivalent-of-unrar-package-rar

"You can unpack RAR files with 7-zip.

Install that with sudo apt install p7zip p7zip-full

Use 7z e my_rar_file to extract the contents. NOTE: 7z can't create rar files."

the 7z e file.rar worked like a charm. Maybe it's time to move away from unrar. 

unrar -V
unrar 0.0.1

Seems to be a really old version too laying there in the repo.

**Comment by stickz** [comment] 2023-01-05 05:15
Nope, no plans to rewrite unrar. If you get ruTorrent v4.0 working and would like to test my changes, please open a new issue report. I'm closing this issue because you're running an unsupported version of ruTorrent.

**Closed by stickz** 2023-01-05 05:15 UTC

**Comment by blixten85** [comment] 2023-01-05 05:48
Am i? Im using 4.0

Den tors 5 jan. 2023 06:15stickz ***@***.***> skrev:
