### ISSUE TITLE
ruTorrent is redownloading loaded torrents from RSS Feed 

### ISSUE THREAD

**Issue by holygamer** [Novik/ruTorrent#1630] opened 2018-01-06 20:17 UTC
I've added an RSS feed to download the last 100 PC games uploaded to IP Torrents. Whenever a new game is uploaded it will also download that.

To get the RSS Feed I clicked on the RSS Feed link in IP Torrents then I select the categories I wanted torrent for then I selected "Download link" instead of "Web link". I then copied the RSS link it gave me into ruTorrent.

Here's a screenshot of my RSS Manager settings:

I've added an RSS feed to download the last 100 PC games uploaded to IP Torrents. Whenever a new game is uploaded it will also download that.

To get the RSS Feed I clicked on the RSS Feed link in IP Torrents then I select the categories I wanted torrent for then I selected "Download link" instead of "Web link". I then copied the RSS link it gave me into ruTorrent.

Here's a screenshot of my RSS Manager settings:

![untitled](https://user-images.githubusercontent.com/4997871/34643591-95d0157a-f31e-11e7-8771-b3d927283702.png)

I used the filter shown as I want ALL newly uploaded PC games.

My problem is that once I've downloaded everything in the feed I select all the torrents with the label "IPT PC Games" and I right-click on one of them and choose "Save To" and select a "Completed" folder I made.  All the selected torrents are then moved to that folder. That way I know that everything in that folder can be transferred to my Google Drive. I then delete the torrent files in ruTorrent. In the feed I then mark everything I downloaded as "Loaded". The problem is that some of them redownload within 24 hours.

What am I doing wrong? 

I used the filter shown as I want ALL newly uploaded PC games.

My problem is that once I've downloaded everything in the feed I select all the torrents with the label "IPT PC Games" and I right-click on one of them and choose "Save To" and select a "Completed" folder I made.  All the selected torrents are then moved to that folder. That way I know that everything in that folder can be transferred to my Google Drive. I then delete the torrent files in ruTorrent. In the feed I then mark everything I downloaded as "Loaded". The problem is that some of them redownload within 24 hours.

What am I doing wrong? I don't want to redownload stuff I already downloaded.

**Comment by s-c-o-o-t** [comment] 2018-01-06 21:22
Requirements:
- A method of obtaining an RSS feed for your favorite tracking site (IPT has a built in one, but sites like TPB you might need to search around Google)
- Torrent client with RSS reader support (and automatic downloading). I am using qBittorrent for this.

Now let's begin! (Again, I will be doing this tutorial with IPT and qBittorrent)
1.Select the big RSS button at the top of the site. http://i.imgur.com/PNaWpy1.png
2.Enter the size of the torrents you want, and select the "Games/PS3" checkbox. (For the size, you can choose whatever you'd like. The disc version will probably be 20gb max, so I did 10-25 gb.)
3.Select the download link radio button and click the "Get RSS Link" button.
4.After doing so, copy the url of your feed and head to your torrent client.
5.In your torrent client, find how to add a new RSS feed. If you're using qBittorrent like me, simply go to View > RSS reader and a new tab for the RSS feed will show up. Then in that tab, click "New Subscription". http://i.imgur.com/xbIRtqE.png
6.Input the URL you just copied and it should add that feed.
7.Now that you've done that, you need to set up the automatic download so it only downloads AW and not every game posted. In qBittorrent, click the "RSS Downloader..." button. http://i.imgur.com/G2sMWrj.png
8.Now you need to add a new rule. Click the + button at the top left to add a new one and just call it "AW". http://i.imgur.com/xW2IykC.png
9.For the rules, the only thing you need is some string that will specify whether the game is AW or not. I would just do "Advanced Warfare". Make sure you apply this rule to your RSS feed! http://i.imgur.com/9xCvJ5W.png
10.After that, click close and you're set. You can edit the settings and change how often it refreshes the feed. The default is 5 minutes which should be good enough.

Try that mate

**Comment by holygamer** [comment] 2018-01-06 21:28
Thanks but doesn't help with my problem. I'm using ruTorrent on a seedbox.

**Comment by s-c-o-o-t** [comment] 2018-01-06 21:28
You can also try this : might be more help for youre need in this matter : 

Either set "ignore subsequent matches" for X days to 7 days assuming a weekly release schedule.
Or set your filter rules up better to ensure you're only getting 1 set of episodes from 1 uploader so there are NO duplicates to mis-download.

In answer to your question, no qbittorrent's RSS feed does NOT keep track of the actual episode names it downloads.
If you get episode 1 for the show then a month later episode 1 gets re-uploaded and enters your feed with FIXED attached to the name of it then qbittorent will see it as a new hit and download it unless its filtered.

As for is it fixable? Yeah, you could make qbittorent automagically advance the episode filter up 1 episode when it hits a match.
Eg found match for S01E01 filter changes from 1x1-; to 1x2-; which should prevent all matches for S01E01 in the future.

May be worth requesting it as a feature on the github (i'll probably do it myself later today when i have time to write something smart up if it doesnt exist by then)

**Comment by holygamer** [comment] 2018-01-07 00:08
Again, none of that helps me. I'm using ruTorrent not qbitorrent.

**Comment by s-c-o-o-t** [comment] 2018-01-07 02:05
(match always) i see you have , of course it will re-download it

**Comment by holygamer** [comment] 2018-01-07 02:24
Match all means download everything in that category that the RSS feed was created from. It doesn't mean keep downloading things already downloaded.

If I'm wrong does setting a "min interval" to 1 day only download newly uploaded torrents that were uploaded within the last day?

**Comment by s-c-o-o-t** [comment] 2018-01-07 03:49
re to #386

**Comment by s-c-o-o-t** [comment] 2018-01-07 03:51
not sure , i would assume so check this : https://github.com/rakshasa/rtorrent/issues/386

**Comment by holygamer** [comment] 2018-01-07 06:18
You said "May be worth requesting it as a feature on the github (i'll probably do it myself later today when i have time to write something smart up if it doesnt exist by then)"

You mentioned before about having a filter to download new episodes, etc. I can't do that as I'm just downloading games. Where do I post a feature request? Basically I would like an RSS setting to only download newly uploaded games and when the torrents are deleted they shouldn't be redownloaded. Perhaps the program can keep a list of the past 100 RSS feed torrents downloaded so it knows not to redownload them.

**Comment by tashkas1** [comment] 2018-03-14 20:27
use filter *.*

**Comment by describe19** [comment] 2018-11-30 10:14
@holygamer did you ever find a solution to this? I am struggling with the same issue.

**Comment by Micdu70** [comment] 2018-11-30 16:10
RSS filter doesn't download RSS marked as `Already loaded`.

I use `/.*/i` as filter.

**Comment by Vastlee** [comment] 2019-02-13 02:46
None of the responses here have addressed the initial issue.
The problem is that things marked "Already Loaded" are seemingly at random changing back to "RSS" status. This is of course a problem because unless you keep & seed what you downloaded forever, it will download them again, and again, and again. Here is an example. 4 hour difference. No filters. Literally just load the feed, mark all loaded & wait.

<img width="1178" alt="rss_bna" src="https://user-images.githubusercontent.com/7232810/52682995-42428900-2ef6-11e9-976b-07cc64e4dd44.png">

**Comment by Novik** [comment] 2019-02-13 15:10
@Vastlee, two possible reasons of this.

1) Your feed (or feeds) owner set a random times for the feed items. Like torrentday.com. Add domains of such servers to the array $feedsWithIncorrectTimes in the plugin's configuration.
2) You have a lot of rss feed's items. And standard value of HISTORY_MAX_COUNT limit (100) is too small for you. Try to increase HISTORY_MAX_COUNT constant in the plugin's configuration.

**Comment by ElusiveZatchmo** [comment] 2019-12-21 19:01
I just want to add to this thread that it's 12/21/2019 and I'm also having this issue

**Comment by jedi256** [comment] 2019-12-29 15:56
I also still have this issue as of 29 Dec 2019. Once I download torrents received via RSS from my seedbox to my home, I label them with the label "Delete." Then I wait to actually delete these same torrents from the seedbox until they no longer exist in the RSS feed(s) (~24 to 72 hours). It's not ideal but it works. I hope the rtorrent developers resolve this problem eventually.

**Comment by koblack** [comment] 2020-03-26 15:32
Just checked after configuration as @Novik suggested, IPT rss working fine. 
b3fe4abf55512c0f406e7ba1920fd8f17ab6f7c5 rss plugin: add IPTorrents to feedsWithIncorrectTimes

**Closed by koblack** 2020-03-26 15:32 UTC
